switches:
  hera-40g-sw5:
    model: '7124sx'
    username: 'admin'
    password: 'admin'
    # vlan usage:
    # 1: default
    # 3: DHCP
    # 10: Correlator data
    # 11: GBT-1U
    # 12: Still uplink
    # >900: Port isolation (unused)
    vlans:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 3
      6: 10
      7: 11
      8: 997
      9: 3
      10: 10
      11: 11
      12: 998
      13: 1
      14: 10
      15: 10
      16: 11
      17: 1
      18: 12
      19: 12
      20: 12
      21: 3
      22: 3
      23: 3
      24: 3
