   
arista7050: &arista7050
  model: '7050qx-32'
  username: 'admin'
  password: 'admin'

front_end_vlans: &front_end_vlans
  1/1: 2
  1/2: 2
  1/3: 2
  1/4: 2
  2/1: 2
  2/2: 2
  2/3: 2
  2/4: 2
  3/1: 2
  3/2: 2
  3/3: 2
  3/4: 2
  4/1: 2
  4/2: 2
  4/3: 2
  4/4: 2
  5/1: 2
  5/2: 2
  5/3: 2
  5/4: 2
  6/1: 2
  6/2: 2
  6/3: 2
  6/4: 2
  7/1: 2
  7/2: 2
  7/3: 2
  7/4: 2
  8/1: 2
  8/2: 2
  8/3: 2
  8/4: 2
  9/1: 2
  9/2: 2
  9/3: 2
  9/4: 2
  10/1: 2
  10/2: 2
  10/3: 2
  10/4: 2
  11/1: 2
  11/2: 2
  11/3: 2
  11/4: 2
  12/1: 2
  12/2: 2
  12/3: 2
  12/4: 2
  13/1: 2
  13/2: 2
  13/3: 2
  13/4: 2
  14/1: 2
  14/2: 2
  14/3: 2
  14/4: 2
  15/1: 2
  15/2: 2
  15/3: 2
  15/4: 2
  16: [2]
  17: [2]
  18: [2]
  19: [2]
  20: [2]
  21: [2]
  22: [2]
  23: [2]
  24: [2]
  25: [2]
  26: [2]
  27: [2]
  28: [2]
  29: [2]
  30: [2]
  31: [2]
  # DHCP uplink
  32: 2

common_vlans: &common_vlans
  # port : vlan(s)
  # vlan = int => untagged
  # vlan = list => tagged, with first list entry the native vlan
  1: 100
  2: 100
  3: 100
  4: 100
  5: 998
  6: 100
  #7/1: 2 Set individually per switch
  # 7/2 is the [NOW UNUSED] uplink to the storage switch
  7/2: 997
  # 7/3 is wired in for one day using GBT-1u(?)
  7/3: 1000
  7/4: 999
  8: 100
  9: 100
  10: 100
  # Ports 11 - 18 are inter-switch links
  # 11-14 -> switch1
  11: [3]
  12: [3]
  13: [3]
  14: [3]
  # 15-18 -> switch2
  15: [3]
  16: [3]
  17: [3]
  18: [3]
  # 19 is overridden by the switch providing DHCP
  19: 100
  20: 100
  # Ports 21-29 are X-engines
  # Ports 21/22 set per-switch
  21: 3
  22: 3
  23: 3
  24: 3
  25: 3
  26: 3
  27: 3
  28: 3
  # Spare X-engine
  29: 100
  # 40g rack-to-rack KDRA switches
  30: 3
  # 31 & 32 are Storage nodes
  31: 3
  32: 3

common_vlan_maps: &common_vlan_maps
  11: {in : [2,3]}
  12: {in : [2,3]}
  13: {in : [2,3]}
  14: {in : [2,3]}
  15: {in : [2,3]}
  16: {in : [2,3]}
  17: {in : [2,3]}
  18: {in : [2,3]}

static_address_table: &static_address_table_ssc
  16: [hera-gpu1-5.forty.pvt, hera-gpu2-5.forty.pvt]
  17: [hera-gpu3-5.forty.pvt, hera-gpu4-5.forty.pvt]
  18: [hera-gpu5-5.forty.pvt, hera-gpu6-5.forty.pvt]
  19: [hera-gpu7-5.forty.pvt, hera-gpu8-5.forty.pvt]
  24: [hera-gpu10-5.forty.pvt, hera-gpu11-5.forty.pvt]
  25: [hera-gpu12-5.forty.pvt, hera-gpu13-5.forty.pvt]
  26: [hera-gpu14-5.forty.pvt, hera-gpu15-5.forty.pvt]
  27: [hera-gpu16-5.forty.pvt, hera-gpu17-5.forty.pvt]
  20: [hera-gpu1-3.forty.pvt, hera-gpu2-3.forty.pvt]
  21: [hera-gpu3-3.forty.pvt, hera-gpu4-3.forty.pvt]
  22: [hera-gpu5-3.forty.pvt, hera-gpu6-3.forty.pvt]
  23: [hera-gpu7-3.forty.pvt, hera-gpu8-3.forty.pvt]
  28: [hera-gpu10-3.forty.pvt, hera-gpu11-3.forty.pvt]
  29: [hera-gpu12-3.forty.pvt, hera-gpu13-3.forty.pvt]
  30: [hera-gpu14-3.forty.pvt, hera-gpu15-3.forty.pvt]
  31: [hera-gpu16-3.forty.pvt, hera-gpu17-3.forty.pvt]

static_address_table_kdra_1: &static_address_table_kdra_1
  # Individual switches now need to know how to get to the catcher since they're a
  #7/2: [catcher]
  21: [hera-gpu1-3.forty.pvt, hera-gpu1-5.forty.pvt]
  22: [hera-gpu2-3.forty.pvt, hera-gpu2-5.forty.pvt]
  23: [hera-gpu3-3.forty.pvt, hera-gpu3-5.forty.pvt]
  24: [hera-gpu4-3.forty.pvt, hera-gpu4-5.forty.pvt]
  25: [hera-gpu5-3.forty.pvt, hera-gpu5-5.forty.pvt]
  26: [hera-gpu6-3.forty.pvt, hera-gpu6-5.forty.pvt]
  27: [hera-gpu7-3.forty.pvt, hera-gpu7-5.forty.pvt]
  28: [hera-gpu8-3.forty.pvt, hera-gpu8-5.forty.pvt]
  29: [hera-gpu9-3.forty.pvt, hera-gpu9-5.forty.pvt]
  30:
    - hera-gpu10-5.forty.pvt
    - hera-gpu11-5.forty.pvt
    - hera-gpu12-5.forty.pvt
    - hera-gpu13-5.forty.pvt
    - hera-gpu14-5.forty.pvt
    - hera-gpu15-5.forty.pvt
    - hera-gpu16-5.forty.pvt
    - hera-gpu17-5.forty.pvt
    - hera-gpu18-5.forty.pvt

static_address_table_kdra_2: &static_address_table_kdra_2
  # Individual switches now need to know how to get to the catcher since they're a
  #7/2: [catcher]
  21: [hera-gpu10-3.forty.pvt, hera-gpu10-5.forty.pvt]
  22: [hera-gpu11-3.forty.pvt, hera-gpu11-5.forty.pvt]
  23: [hera-gpu12-3.forty.pvt, hera-gpu12-5.forty.pvt]
  24: [hera-gpu13-3.forty.pvt, hera-gpu13-5.forty.pvt]
  25: [hera-gpu14-3.forty.pvt, hera-gpu14-5.forty.pvt]
  26: [hera-gpu15-3.forty.pvt, hera-gpu15-5.forty.pvt]
  27: [hera-gpu16-3.forty.pvt, hera-gpu16-5.forty.pvt]
  28: [hera-gpu17-3.forty.pvt, hera-gpu17-5.forty.pvt]
  29: [hera-gpu18-3.forty.pvt, hera-gpu18-5.forty.pvt]
  30:
    - hera-gpu1-5.forty.pvt
    - hera-gpu2-5.forty.pvt
    - hera-gpu3-5.forty.pvt
    - hera-gpu4-5.forty.pvt
    - hera-gpu5-5.forty.pvt
    - hera-gpu6-5.forty.pvt
    - hera-gpu7-5.forty.pvt
    - hera-gpu8-5.forty.pvt
    - hera-gpu9-5.forty.pvt

dynamic_address_table: &dynamic_address_table
  dynamic:
    - hera-gpu1-3.forty.pvt
    - hera-gpu2-3.forty.pvt
    - hera-gpu3-3.forty.pvt
    - hera-gpu4-3.forty.pvt
    - hera-gpu5-3.forty.pvt
    - hera-gpu6-3.forty.pvt
    - hera-gpu7-3.forty.pvt
    - hera-gpu8-3.forty.pvt
    - hera-gpu9-3.forty.pvt
    - hera-gpu10-3.forty.pvt
    - hera-gpu11-3.forty.pvt
    - hera-gpu12-3.forty.pvt
    - hera-gpu13-3.forty.pvt
    - hera-gpu14-3.forty.pvt
    - hera-gpu15-3.forty.pvt
    - hera-gpu16-3.forty.pvt
    - hera-gpu1-5.forty.pvt
    - hera-gpu2-5.forty.pvt
    - hera-gpu3-5.forty.pvt
    - hera-gpu4-5.forty.pvt
    - hera-gpu5-5.forty.pvt
    - hera-gpu6-5.forty.pvt
    - hera-gpu7-5.forty.pvt
    - hera-gpu8-5.forty.pvt
    - hera-gpu9-5.forty.pvt
    - hera-gpu10-5.forty.pvt
    - hera-gpu11-5.forty.pvt
    - hera-gpu12-5.forty.pvt
    - hera-gpu13-5.forty.pvt
    - hera-gpu14-5.forty.pvt
    - hera-gpu15-5.forty.pvt
    - hera-gpu16-5.forty.pvt

switches:
  hera-40g-sw1:
    <<: *arista7050
    vlans:
      <<: *common_vlans
      # DHCP uplink
      7/1: 4 
      19: 4
    vlan_map:
      <<: *common_vlan_maps
    address_table:
      <<: *static_address_table_kdra_1
      # switch 1 forwards catcher packets to switch 3
      30: [catcher]
  hera-40g-sw2:
    <<: *arista7050
    vlans:
      <<: *common_vlans
      7/1: 888
    vlan_map:
      <<: *common_vlan_maps
    address_table: *static_address_table_kdra_1
  hera-40g-sw3:
    <<: *arista7050
    vlans:
      <<: *common_vlans
      7/1: 888
    vlan_map:
      <<: *common_vlan_maps
    address_table:
      <<: *static_address_table_kdra_2
      # switch 3 has a direct-connect to the catcher
      32: [catcher]
  hera-40g-sw4:
    <<: *arista7050
    vlans:
      <<: *common_vlans
      7/1: 888
    vlan_map:
      <<: *common_vlan_maps
    address_table: *static_address_table_kdra_2
  hera-ssc-sw1:
    <<: *arista7050
    address_table: *static_address_table_ssc
    vlans: *front_end_vlans
  hera-ssc-sw2:
    <<: *arista7050
    address_table: *static_address_table_ssc
    vlans: *front_end_vlans
   
