# VLANs fof the 10Gb switch in the head/storage rack
switches:
  hera-40g-sw5:
    model: '7124sx'
    username: 'admin'
    password: 'admin'
    # vlan usage:
    # 1: default
    # 3: DHCP
    # 10: Correlator data
    # 11: GBT-1U
    # 12: Still uplink
    # >900: Port isolation (unused ports)
    vlans:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 3
      # Data now doesn't flow through this switch.
      # but the ports are still connected so vlan them to
      # disable
      6: 901
      7: 11
      8: 997
      9: 3
      10: 902
      11: 11
      12: 998
      13: 1
      14: 903
      15: 904
      16: 11
      17: 1
      18: 12
      19: 12
      20: 12
      21: 3
      22: 3
      23: 3
      24: 3
